# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib mongolitedt
NULL

R_unlock_environment <- function(env) {
    .Call('_mongolitedt_R_unlock_environment', PACKAGE = 'mongolitedt', env)
}

