# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_unlock_environment <- function(env) {
    .Call('mongolitedt_R_unlock_environment', PACKAGE = 'mongolitedt', env)
}

